### ISSUE TITLE
Missing `App_Data`

### ISSUE THREAD

**Issue by david-poindexter** [enfJoao/GDPR-cookie-consent-for-2sxc-and-DNN#1]
This repo seems to be missing the `App_Data` folder.  This contains an `app.xml` file (and possibly an `app.json` file) that would be important to anyone wishing to use this app.  The template file alone is not enough and the other files contain all the important app data.  If you need help with this, I am happy to help.  Long story short though, you can...

1. Go to app Admin
2. Go to `App` tab
3. Scroll to bottom
4. Click `Save state`

<img width="236" alt="image" src="https://user-images.githubusercontent.com/4568451/230743318-40a8b7f0-e036-4661-b123-fb9c16003c38.png">

5. Use the app folder in `/Portals/<PortalId>/2sxc/<AppName>` as your `git` repo

**Comment by enfJoao** [comment]
Thanks.
I thought people would just download the release app to import into a portal.
I uploaded the entire app folder into git.

**Comment by david-poindexter** [comment]
Wonderful - thank you!
